### ISSUE TITLE
Resolve headless eclipse build environment inconsistencies

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#101]
- remove `*.headless` project from `core` plugins as it was only an experiment
- remove unused `product` definition in headless.api project's MANIFEST.MF
- resolve inconsistencies in `gamma.apu.headless.product`: remove windows dependencies, update product id
- in the `headless_gamma_linux_target.target` target platform definition: remove unused dependencies
- update the headless eclipse build documentation with these changes and remove irrelevant parts of it.

**Comment by grbeni** [comment]
I have merged the corresponding PR #102.
