### ISSUE TITLE
Add Annotations to TimeoutDeclarations

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#103]
Sometimes it might be useful to mark certain timeout declarations as control variables in XSTS. Therefore, we should add Annotations to TimeoutDeclaration, and transform them to XSTS: 

1. In Gamma to Lowlevel transformation: https://github.com/ftsrg/gamma/blob/master/plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/StatechartToLowlevelTransformer.xtend#L206
2. In Lowlevel to XSTS transformation: https://github.com/ftsrg/gamma/blob/master/plugins/xsts/hu.bme.mit.gamma.lowlevel.xsts.transformation/src/hu/bme/mit/gamma/lowlevel/xsts/transformation/LowlevelToXstsTransformer.xtend#L475

**Comment by grbeni** [comment]
I introduced "hidden" annotations (ScheduledClockVariableDeclarationAnnotation) to XSTS variables that are considered during the serialization of the XSTS model in 5ac68882ac9a04d7bc2d8bb6679188f6f114b1f4 and result in `ctrl` annotations. I wanted to keep this functionality out of the Gamma language (TimeoutDeclaration class) as it addresses low-level model checker specific options and problems.

**Comment by benedekh** [comment]
Looks good. Please discuss it with @miondokm if it is a good idea to implicitly convert the clock variables to ctrl variables. Also decide what shall happen with the implementation provided in #104.

**Comment by grbeni** [comment]
Well, as we discussed, possibly the best option would be to introduce a new annotation, e.g., `clk`, to denote clock variables and Theta can represent the variable as it sees optimal based on the expectations of how clock variables should be handled. This solution supports the above workflow, only a single string has to be replaced in the serialization class.
As for the implementation, we can keep it on the current branch and get back to it if we realize that we actually have to add annotations to `TimeoutDeclaration`s.

**Comment by grbeni** [comment]
Okay, I will do as suggested.
