### ISSUE TITLE
Allow model checker parametrizations in the ggen file

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#105]
It would be useful if the model checking expert user could specify several parametrizations that are used to call the respective model checkers in parallel (see UppaalValidation and ThetaValidation classes).

Please note the security implications of this feature request, i.e. the parametrizations should be validated, because they will be used as arguments to a CLI application.

/cc @grbeni

**Comment by grbeni** [comment]
I agree, the underlying implementation supports this functionality, only the UI will have to be prepared. Nevertheless, the question of _how_ we want to support this on the UI should be addressed as e.g., the specification of parameters like `--domain EXPL_PRED_COMBINED --autoexpl NEWOPERANDS --initprec CTRL` cannot be expected from the user. The sanitization of inputs, as you mentioned, also has to be addressed.

**Comment by benedekh** [comment]
From our perspective the ggen file is interesting. We expect that our project will generate the corresponding parameters, and Gamma shall process them. It will be our problem, not Gamma's what parameters we put there.

**Comment by grbeni** [comment]
The FR has been implemented, check out ecb740b8948e8365f2da027895be05d753d5d77a.

**Comment by benedekh** [comment]
@grbeni Thank you for the quick adoption. Three comments:

1. Could you provide an example ggen on how to provide more verfication arguments, i.e. `verification-argument`?
2. Instead of initializing the array with size 0, it might be more optimal to initialize it with `verificationArguments.length`: https://github.com/ftsrg/gamma/commit/ecb740b8948e8365f2da027895be05d753d5d77a#diff-458d7fe66376bf7308d98ff82481b89707fbde7a30b85f7a5a8a19f7b478cccaR118
3. Why don't we need to sanitize UPPAAL arguments? https://github.com/ftsrg/gamma/commit/ecb740b8948e8365f2da027895be05d753d5d77a#diff-f4202aff561bc9fc9d468904765205fd8ed42a490ed4f65f4a58be5842b036ddR17

**Comment by grbeni** [comment]
1. Here is an example of executing (portfolio) verification with Theta using three different parameterizations:
```
verification {
	language : Theta
	file : "Crossroad-Theta.xsts"
	query-file : "ThetaCustomQueries.prop"
	test-language : java
	verification-argument : "--domain PRED_CART --refinement SEQ_ITP"
	verification-argument : "--domain EXPL --refinement SEQ_ITP --maxenum 250"
	verification-argument : "--domain EXPL_PRED_COMBINED --autoexpl NEWOPERANDS --initprec CTRL"
}
```
If there are no `verification-argument`s in the verification task, default arguments are used (just like before).

2. Good point, I fixed it in  e0d7d0ebcd00efcdded87daee51aa9084a3d4097.

**Comment by benedekh** [comment]
Great, thank you very much.

**Comment by grbeni** [comment]
@benedekh If you find this extension adequate (e.g., when using it during your measurement campaign), close this issue, please.

**Comment by benedekh** [comment]
@grbeni: ok, I'll check it soon.

**Comment by benedekh** [comment]
It seems to be working well. Thank you for the quick implementation, @grbeni!
