### ISSUE TITLE
Fix MANIFEST.MF and product definition in headless.api project

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#106]
After renaming hu.bme.mit.gamma.codegenerator.java and hu.bme.mit.gamma.codegenerator.java.util to hu.bme.mit.gamma.codegeneration.java and hu.bme.mit.gamma.codegeneration.java.util, the MANIFEST.MF and the .product definition in the headless.api project became inconsistent (missing depdendencies).

@grbeni could you please resolve these inconsistencies?

**Comment by grbeni** [comment]
As I can see, the corresponding PR seems to fix this issue, thank you for the fix.
