### ISSUE TITLE
Move PredicateHandler to a separete util file

### ISSUE THREAD

**Issue by turi-mate** [ftsrg/gamma#112]
I'm working a transformer for Promela language and to serialize `HavocAction` I should use a similar class that handles different values of integer variables. I think it would be useful to move `PredicateHandler` in a separate util file, so that it can be used for possible next language transformers.

**Comment by grbeni** [comment]
I did the extraction in 672c2a00f4aa66c751bd1e56bcd48e28d535adb5, could you check it out?

**Comment by turi-mate** [comment]
I checked the extraction and I think it is good. Thank you!
