### ISSUE TITLE
Traceability issues during C code generation

### ISSUE THREAD

**Issue by nagyl1999** [ftsrg/gamma#159]
Some information might be unavailable in XSTS, for example:

- event and event parameter mappings
- event and event id mappings in message queues
- references from message queue arrays to their size

**Comment by grbeni** [comment]
No. 1 and 3 are addressed in cd25ac106c03c791a2d95d3a4b56d1b69556b5bf. No. 2 will require further investigation.

**Comment by nagyl1999** [comment]
In addition to the XSTS model, the C generator eventually started using the initial Gamma statechart or composition model. Consequently, features No. 1 and 2, while useful, became unnecessary.
