### ISSUE TITLE
Visualization issues for raised events in execution traces

### ISSUE THREAD

**Issue by grbeni** [ftsrg/gamma#162]
We should indicate that raised events in execution traces do not have a particular ordering in synchronous systems, i.e., if `A.a`, `B.b` and `C.c` are all raised, they can appear in any order in the trace with the same meaning.

**Comment by marci543** [comment]
A possible [PlantUML syntax](https://plantuml.com/sequence-diagram#425ba4350c02142c) might be:
- `par` of every message,
- `group` with custom label.

**Comment by grbeni** [comment]
See [d315633](https://github.com/ftsrg/gamma/commit/d3156335cb9cc79fa9766a16faddfd09bdd3315d) for the implemented solution.
