### ISSUE TITLE
Swallowed exception

### ISSUE THREAD

**Issue by arminzavada** [ftsrg/gamma#165]
Swallowed exception hides valuable information.

https://github.com/ftsrg/gamma/blob/4f66c3ffd66a478aeb47e47ba9e7173932707e56/plugins/core/hu.bme.mit.gamma.language.util/src/hu/bme/mit/gamma/language/util/linking/GammaLanguageLinker.java#L92-L93

This line swallows the exception, assuming, that is means the path is incorrect. However, an exception could also be thrown if the path is correct, but the resource load failed for other reasons, in which case the details are valuable for the user to fix the issue.

Solution:
Check the exception cause if it is of type `FileNotFoundException`.

**Comment by grbeni** [comment]
It was more complicated than this, but I introduced better exception handling in 4e6a368afe0ab3bb1c6f7df8e18feca294653998.

**Comment by grbeni** [comment]
Actually, invalid paths cause different kinds of exceptions in the case of different models, e.g., Yakindu. Thus, I reverted the changes in 99d1c6b8984f0b9cf7488d65c8ac90c86b2d3bb0.
