### ISSUE TITLE
Display user-friendy error messages when a verification backend is not found

### ISSUE THREAD

**Issue by vincemolnar** [ftsrg/gamma#173]
Currently, an uninstalled backend will cause an exception that is directly displayed to the user:

> An unexpected error occured: Cannot invoke "hu.bme.mit.gamma.util.ScannerLogger.cancel()" because "this.resultLogger" is null
> Cannot invoke "hu.bme.mit.gamma.util.ScannerLogger.cancel()" because "this.resultLogger" is null

Instead of this, the plugin should detect that the process it wanted to start does not exist and display an appropriate error message, preferably directing the user to the website where they can install the missing tool.

**Comment by grbeni** [comment]
Fixed in f1252f55aa946a1fcd6acb4e1f437bff4493391d-
