### ISSUE TITLE
Theta exception handling

### ISSUE THREAD

**Issue by hajduakos** [ftsrg/gamma#19]
Since Theta v2.4.0, the exception reporting of Theta has the following format:

`<EXCEPTION_TYPE> occurred, message: <MESSAGE>`

Furthermore, if the `--stacktrace` option is given, a full stack trace is also printed below. I think in such cases it would be the best to only display the first line to the user (because that's a summary) and have some button where they can click for all the details (the stack trace). Note, that in some cases the message can be empty, this is the fault of Theta and such cases should be fixed within Theta to provide a meaningful message.

Also related to #18

**Comment by hajduakos** [comment]
A remark: we are also flexible with the error reporting format of Theta. @grbeni if you have something else in mind (e.g., something easier to parse), let us know.

**Comment by grbeni** [comment]
I like this format. I have not thought of introducing the automatic parsing of error messages in Gamma, so the message format and the message should be intuitive to the user, and I believe the current one is okay (naturally, the message should be easily interpretable by users).
I guess the stack trace can be useful to Theta developers for debugging potential bugs, but it is not too disturbing for users either (if the stack trace is separated from the error message, which can be achieved easily), so I approve #18.

**Comment by hajduakos** [comment]
Okay. I also think that for now having the stack trace below is not that disturbing. Then we can close this issue and reopen later if needed.
