### ISSUE TITLE
Wrong vendor and name fields in projects' MANIFEST.MF

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#21]
In projects:

```
hu.bme.mit.gamma.lowlevel.xsts.transformation.traceability
hu.bme.mit.gamma.yakindu.transformation.traceability
hu.bme.mit.gamma.uppaal.transformation.traceability
hu.bme.mit.gamma.statechart.lowlevel.model
hu.bme.mit.gamma.xsts.model
```

the Name and Vendor fields in the MANIFEST.MF are:

```
Name: %pluginName
Vendor: %providerName
```

In the `hu.bme.mit.gamma.validation.validation` project the Name and Vendor fields in the MANIFEST.MF are:

```
Name: hu.bme.mit.gamma.validation.validation
Vendor: (empty)
```

instead of the meaningful values, the other projects have.

**Comment by grbeni** [comment]
`hu.bme.mit.gamma.validation.validation` is a project generated by VIATRA (not tracked in the repository). Therefore, I cannot set its Name and Vendor values. Nevertheless, I have tended to the Manifest values of the other mentioned projects.
