### ISSUE TITLE
Variable declarations after a Choice is duplicated in XSTS

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#24]
I have the following (Java Script) actions, that are transformed to a correct gamma action series, see [gamma.txt](https://github.com/ftsrg/gamma/files/5792579/gamma.txt) (gsm) model attached. However, if the .gsm is transformed into an XSTS then the `gen3, gen4, gen7, gen12,  gen14` variable declarations are duplicated in the XSTS, see [bug.txt](https://github.com/ftsrg/gamma/files/5792580/bug.txt) (xsts) attached. All these variables are after the if-else block, therefore it might be a bug.

```
var gen1 = false;
var gen2 = 11;
var gen6 = gen1;
var gen5 = gen2;
var gen9 = 1;
var gen10 = gen9;
data = gen10;
var gen13 = gen5;
data = gen13;
var gen16 = -5;
if (data == 11) {
	data = 22;
} else if (!(data == 11)) {
	data = 4;
}
var gen12 = gen16;
var gen14 = gen16;
var gen7 = gen6;
var gen4 = gen14;
var gen3 = gen12;
falser = gen7;
replaced = gen3;
random = gen4;
```

**Comment by grbeni** [comment]
Does this still pose a problem after the introduction of local variable optimization?

**Comment by benedekh** [comment]
Thanks to variable inlining, this issue cannot be reproduced anymore. Should this problem occur, despite commit 3493e051, I'll reopen the issue.
