### ISSUE TITLE
Scheduling constraint results in an empty ExecutionTrace

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#25]
If I instantiate the `Gamma2XSTSUppaalTransformerSerializer` with `schedulingConstraint = 500`, and check a reachability property on a model that has timing, then the resulting Execution Trace is empty. The necessary artifacts (GSM and UPPAAL models, CTL query) are in [emptyTrace.zip](https://github.com/ftsrg/gamma/files/5792602/emptyTrace.zip)

![image](https://user-images.githubusercontent.com/8940487/104123418-69589e00-534b-11eb-9c10-d2d129e1c797.png)

However, if I do the same without any scheduling constraint, then the Execution Trace looks as it should. The necessary artifacts (GSM and UPPAAL models, CTL query) are in  [nonEmptyTrace.zip](https://github.com/ftsrg/gamma/files/5792601/nonEmptyTrace.zip)

![image](https://user-images.githubusercontent.com/8940487/104123450-88efc680-534b-11eb-8190-30bc49abb59b.png)

Therefore, I think there might be a bug somewhere.

-----

The original state machine looks like this:

![image](https://user-images.githubusercontent.com/8940487/104123553-1e8b5600-534c-11eb-839e-22c146c4e5f8.png)

The used "act" Activity is rather simple:

![image](https://user-images.githubusercontent.com/8940487/104123565-31058f80-534c-11eb-8dfd-e4aa361898c4.png)

**Comment by grbeni** [comment]
I could not reproduce this bug. Maybe this way a bug on the MCaaS side similar to the one presented in Issue #36?

**Comment by benedekh** [comment]
No, it was before running many Theta instances in parallel. Nevertheless I could not reproduce the bug ever since, therefore we may close this issue.
