### ISSUE TITLE
Support local variables

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#27]
It would be nice, if variables created by VariableDeclarationStatements were handled as _local_ variables in Gamma. Although they are supported by the action language, in the transformations for XSTS and UPPAAL, they are treated as _global_ variables which causes some problems, e.g. variable names cannot be reused in different action Blocks, the variable can be used outside of its declaring action Block, etc.

This feature would help handling the semantics of local variables correctly.

**Comment by grbeni** [comment]
We are waiting for their introduction into XSTS.

**Comment by grbeni** [comment]
Local variables have been introduced into XSTS and the Gamma mapping now builds on this feature: 9bb66588a6c27a45181e85bdabaaf91c74d1af57.
