### ISSUE TITLE
Optimize variables created by VariableDeclarationStatement

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#28]
There are several cases, when variables created by VariableDeclarationStatements could be optimized. They could be inlined into other statements or expressions, therefore eliminating the duplicate variables and reducing the state-space complexity (the complexity of checking their values), esp. in UPPAAL.

**Comment by grbeni** [comment]
Some optimization algorithms have been introduced. Nevertheless, this issue will pose lesser problems after local variables get introduced in XSTS.

**Comment by grbeni** [comment]
Local variables have been introduced in 9bb66588a6c27a45181e85bdabaaf91c74d1af57, the optimization problem should pose lesser challenges (or maybe none at all) now as Theta can handle these variables "internally".
