### ISSUE TITLE
ActionTransformer may not terminate

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#29]
Gamma to Lowlevel Statechart [ActionTransformer](https://github.com/ftsrg/gamma/blob/dev/plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/ActionTransformer.xtend) may not terminate if there is a non-recursive if-else Statement or a ChoiceStatement in the containment hierarchy of Actions. 

The reason for that is, the `LinkedList<Action> following` may grow arbitrarily long, especially when the `following` list is repetitively transformed in multiple blocks/branches after each other: see [line#273](https://github.com/ftsrg/gamma/blob/dev/plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/ActionTransformer.xtend#L273), [line#325](https://github.com/ftsrg/gamma/blob/dev/plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/ActionTransformer.xtend#L325), [line#413](https://github.com/ftsrg/gamma/blob/dev/plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/ActionTransformer.xtend#L413), [line#532](https://github.com/ftsrg/gamma/blob/dev/plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/ActionTransformer.xtend#L532).

/cc @Varadbal, @grbeni

**Comment by grbeni** [comment]
The old action transformation process was completely reorganized, 1d40d25d75a6d70d168db3cf2720bc7446e7d94f (or potentionally previous commits) should fix this.
