### ISSUE TITLE
Stable transformation and verification of ForStatements

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#34]
As discussed on an internal meeting on 09.02.2021 with the developer team of Gamma, the transformation of `ForStatement` to Theta and UPPAAL (via the lowlevel-xsts transformation chain) is not well-tested yet. 

Please let us know when the transformation and verification are mature enough, so that we can use `ForStatement`s in our model.

**Comment by grbeni** [comment]
We are waiting for the introduction of for statements in XSTS.

**Comment by grbeni** [comment]
1d40d25d75a6d70d168db3cf2720bc7446e7d94f should fix this.
