### ISSUE TITLE
VariableDeclarationStatements with the same name result in duplicate declarations in XSTS

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#35]
If you have multiple `VariableDeclarationStatement`s which have the same name, then they will be declared multiple times in the XSTS. If we use the lowlevel-xsts transformation chain and would like to use UPPAAL in the end, then the resulting NTA have duplicate variable declarations, which is an error.

**Comment by grbeni** [comment]
Fixed in 3493e051e751121a8fca523e7ff107d93e5c8ca0.

**Comment by benedekh** [comment]
Reopening this issue, because the Gamma -> XSTS transformation flattens the Blocks in the same hierarchy. Therefore, if two Variable Declaration Statements declare variables with the same name in differnt blocks, then they will be merged into the same block. If we verify verify this XSTS with Theta, then since version 2.12 we get `Could not parse XSTS: Symbol b is already declared in this scope` error.

Commit  3493e05 does not solve this issue.

Example code snippet: `{ var a = 1; { var b = 42; } var c = 43; { var b = 41; }}`

[example.gsm.txt](https://github.com/ftsrg/gamma/files/6109780/example.gsm.txt)

**Comment by benedekh** [comment]
As discussed today with @grbeni, flattening is necessary due to scalability reasons. Therefore this issue will be resolved on the user-side by suffixing the variables.
