### ISSUE TITLE
Variable inlining is faulty

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#38]
I've found the following variable inlining bug:

if we take the following actions represented as Java Script code:

![image](https://user-images.githubusercontent.com/8940487/108121633-6ae05900-70a3-11eb-89f7-9af85a3e087a.png)

then after inlining the variables, the XSTS does not contain a statement that would correspond to `gen15 = gen20;`. It only contains the declaration of gen15, and its assignment to gen6. Assignments corresponding to 2 and 3 in the figure, are missing.

GSM model:  [inlining.gsm.txt](https://github.com/ftsrg/gamma/files/5991714/inlining.gsm.txt)

**Comment by benedekh** [comment]
If I disable variable inlining in LowlevelToXSTSTransformer.optimizeActions, then it works correct.

**Comment by grbeni** [comment]
Could you check out if f90e40c2e6b8b3682c31f289258eadfc9dea976e solves this issue?

**Comment by benedekh** [comment]
Works well, thank you for the quick fix!
