### ISSUE TITLE
Create command-line Gamma application

### ISSUE THREAD

**Issue by grbeni** [ftsrg/gamma#39]
In order to create a command-line Gamma application, we plan to
- create an environment where a headless Gamma can be exported from the source plugins (to enable the execution of Gamma tasks using the command-line),
- integrate the headless Gammi application into an OpenAPI-based webserver,
- create a Docker image for the sake of easy shipping.

**Comment by csuvi98** [comment]
The headless version of Gamma can be exported and executed, on Windows and Linux systems. An OpenAPI webserver was created, which can issue commands to the headless Gamma on Windows systems. The execution is also possible using a Linux based Docker image (currently withouth the OpenAPI webserver).

**Comment by grbeni** [comment]
The Docker image containing all the aforementioned functionalities can be found at https://hub.docker.com/repository/docker/ftsrggamma/headless-gamma.
