### ISSUE TITLE
Sequence of actions on transitions are reversed during Yakindu-Gamma transformation

### ISSUE THREAD

**Issue by nyikasandor** [FTSRG/gamma#4]
# The Problem
The problem occur after the execution of the Yakindu - Gamma transformation, with the help of the .ggen file
The order in witch the actions on state transitions are supposed to be executed in, are reversed in the Gamma .gcd file.

## Example
After transforming the model bellow:

![image](https://user-images.githubusercontent.com/35967707/70055118-30db8200-15d9-11ea-8768-431e09ea1be6.png)

The result of the transformed transitions in Gamma language:

`	transition from StateA to StateB when timeout StateATimeout2 / i := 0;
`
`	transition from StateB to StateA when timeout StateBTimeout1 / j := i; i := i + 1;
`

The expected result was:

`	transition from StateA to StateB when timeout StateATimeout2 / i := 0;
`
`	transition from StateB to StateA when timeout StateBTimeout1 / i := i + 1; j := i;
`

## Affects 
This affects the code generation, and possibly other features too.

**Comment by grbeni** [comment]
I have fixed the issue in 7cd4088ebba1416e4dd8510ec3ddcd72d8bf6b61.
