### ISSUE TITLE
Introduce "inState" condition

### ISSUE THREAD

**Issue by vincemolnar** [ftsrg/gamma#40]
We cannot avoid anymore to support "inState" conditions in guard expressions. In SysML, this is used to enable a transition only if the state machine is in a given state (which is normally in another orthogonal region).

**Proposed syntax:** `inState(<qualified state name>)` which is a Boolean expression.

**Validation rules:** The referenced state must be in the same state machine component (error) and shall not be in the same region (warning).

**Proposed semantics:** `inState(s)` is true _iff_ the state configuration _at the beginning of the run-to-compeltion step_ contains the referenced state.

**How to realize in the XSTS mapping:** The guard should refer to the unprimed control variable of the containing region and compare it to the referenced state. Therefore, this value has to be stored in a local variable at the beginning of the RTC step, which can be used in the assumption.

**Example:** `inState(r.s)` where `r` is a region and `s` is a state in it will be replaced with `r_source == s`, where `r_source` is a local variable defined in the beginning of the XSTS transition as `r_source = r`.

**Remarks:** By using the state configuration at the beginning of the RTC step, we can avoid race conditions which could occur during the computation of the next state configuration, when we leave a state before or after the corresponding `inState` expression is evaluated. This is not a concern if the event triggering the transition guarded by an `inState` expression does not leave the referenced state or its parents (except maybe by means of the transition with the `inState` guard).

**Comment by grbeni** [comment]
d0475b78755e2e8a939b7bcc106fb68eb238def0 introduces a solution where the state reference refers to the state configuration of the actual system state. It could be extended to refer to the state configuration at the beginning of the run-to-completion step, but this would introduce semantic inconsistencies e.g., into the guard expressions of transitions. E.g., in `[a > 10 && in-state(B.c)]`, `a > 10` would refer to the actual state whereas `in-state(B.c)` would refer to the state at the beginning of the run-to-completion step.

**Comment by vincemolnar** [comment]
I suggest to make this a semantic variant with a corresponding annotation. I'll open a new issue.

**Comment by grbeni** [comment]
See the result in #48.
