### ISSUE TITLE
Inconsistent UTF-8 encoding

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#42]
Some template strings have not been replaced in 4f83335, e.g. in [XstsUppaalBackAnnotator](https://github.com/ftsrg/gamma/blob/dev/plugins/core/hu.bme.mit.gamma.uppaal.verification/src/hu/bme/mit/gamma/uppaal/verification/XstsUppaalBackAnnotator.xtend), [Trace](https://github.com/ftsrg/gamma/blob/dev/plugins/xsts/hu.bme.mit.gamma.lowlevel.xsts.transformation/src/hu/bme/mit/gamma/lowlevel/xsts/transformation/Trace.xtend). This issue fixes the missing replacements.

**Comment by grbeni** [comment]
Merged in the PR.
