### ISSUE TITLE
Add semantic variation point: evaluation time of guards

### ISSUE THREAD

**Issue by vincemolnar** [ftsrg/gamma#48]
Since we could not come up with objective reasons to evaluate inState expressions (see issue #40) at the beginning of a run-to-completion step or when firing the transition, it would be best to make this parameterizable.

**Proposed syntax:** `@GuardEvaluation = [ BEGINNING_OF_STEP | ON_THE_FLY ]`

**Proposed semantics:** When `@GuardEvaluation` is set to `BEGINNING_OF_STEP`, guard conditions are evaluated based on the states and variable valuations _at the beginning of the execution step_. If it is set to `ON_THE_FLY`, they are evaluated based on the current state and variable valuations at the moment of firing the transition (as it was implemented before).

**How to realize in the XSTS mapping:** To implement `BEGINNING_OF_STEP`, the guard should refer to the unprimed control variable of the containing region and compare it to the referenced state in case of `inState` expressions and use the unprimed variables to refer to the their initial value. Therefore, these values have to be stored in local variables at the beginning of the RTC step, which can be used in the assumption.

**Remarks:** I have some concerns about the current implementation. When is a guard exactly evaluated? Examples to consider are: orthogonal regions, peusdonodes (e.g. decision) and entering or exiting complex states through initial/history states or final states (in the future), with entry and exit actions.

**Comment by grbeni** [comment]
Introduced in 44ca0417d64305228a09e9066197dbe2057c3861.
