### ISSUE TITLE
Old Eclipse link in gamma/plugins/README

### ISSUE THREAD

**Issue by szondakata** [ftsrg/gamma#53]
the link in gamma/plugins/README links to the old, 2020-09 Eclipse IDE (https://www.eclipse.org/downloads/packages/release/2020-09/r/eclipse-ide-java-and-dsl-developers)

correct: https://www.eclipse.org/downloads/packages/release/2021-03/r/eclipse-ide-java-and-dsl-developers

**Comment by grbeni** [comment]
Fix in d0e314b9d7ca5c59d59ea35fa8a28b3ca316fa12.
