### ISSUE TITLE
Generated interfaces may overwrite each other

### ISSUE THREAD

**Issue by szkupienpeti** [ftsrg/gamma#56]
Java code generation generates the .java files of Gamma interfaces to the same package (*.interfaces). As a result, if there are interfaces with the same name in the package of different statemachines (which is valid) the generated code won't work because the previously generated files will be overwritten.

Generating every interface to its own container package (instead of *.interfaces) could be a solution.

**Comment by grbeni** [comment]
Could you check out if 99ebb1c3a8ebbcf0e30dea24519aa51a870d9b83 solves the problem?

**Comment by szkupienpeti** [comment]
Yes, it solved.
