### ISSUE TITLE
XstsDerivedFeatures.getReferredVariables may throw UnsupportedOperationException

### ISSUE THREAD

**Issue by szkupienpeti** [ftsrg/gamma#61]
The `getReadVariables` method may return `Collections.emptySet()`, which is immutable, so calling `addAll` on it may cause an exception.

**Comment by grbeni** [comment]
The question is whether we should go with #61 or the `getReadVariables` method should return `new HashSet<VariableDeclaration>()`.
In every case, it is important to keep it consistent with the `getWrittenVariables` method.

**Comment by grbeni** [comment]
Merged the PR, closing this issue.
