### ISSUE TITLE
Missing context menu entry "Gamma Commands" for .ggen files

### ISSUE THREAD

**Issue by z3rone** [ftsrg/gamma#73]
I'm trying the "User Guide and Tutorial for the Gamma Statechart Composition Framework" and facing a problem in section 3.

When trying to generate the artifacts for a statechart, the according context menu entry is not present when i right-click the .ggen file. (see image)

For .gcd and .sct files the Gamma Commands are displayed.

Eclipse  version 2021-03 (4.19.0)
VIATRA version 0.25.0.202012091732

![image](https://user-images.githubusercontent.com/5370750/120479954-d0d0c200-c3ae-11eb-8e75-6ff21569aae2.png)

**Comment by grbeni** [comment]
Are you sure you are using the correct Yakindu version 3.5.13? It does not work with 4.0. See the documentation:

Install the Yakindu Statechart Tools 3.5.13. from update site: http://updates.yakindu.com/statecharts/releases/3.5.13. From the `YAKINDU Statechart Tools Standard Edition` package, choose

- YAKINDU Statechart Tools,
- YAKINDU Statechart Tools Base,
- YAKINDU Statechart Tools Java Code Generator and
- AKINDU License Integration For Standard Edition subpackages.

**Comment by z3rone** [comment]
What documentation are you referring to?

I cannot find any instructions by itemis, how to install YAKINDU in an existing eclipse instance. In the User Guide and Tutorial it just says "Install [...] the Yakindu Statechart Tools (version 3.5.13)" and "Gamma is tested to work with Eclipse 2021-03" (my version).

It's true though, that YAKINDU does not work in my Gamma Eclipse installation, but I'm using a separate YAKINDU installation to work with this. That is a pre-build version from [here](https://updates.yakindu.org/statecharts/products/professional/3.5.13/) and it says in runs on Eclipse Platform version 4.9.0.v20180906-1121.

**Comment by grbeni** [comment]
Instructions can be found at https://github.com/ftsrg/gamma/blob/dev/plugins/README.md.

Here is the part that specifies how you can install Yakindu from inside Eclipse: 

_Install the following ... packages. The Install window can be opened via the Help > Install New Software... menu item. In the Install window, click Add..., and paste the necessary URL in the Location text field._

The URL is this: _http://updates.yakindu.com/statecharts/releases/3.5.13_. From the YAKINDU Statechart Tools Standard Edition package choose
- YAKINDU Statechart Tools,
- YAKINDU Statechart Tools Base,
- YAKINDU Statechart Tools Java Code Generator and
- YAKINDU License Integration For Standard Edition subpackages.

**Comment by fandras** [comment]
I had the same issue, but the installation of the **PlantUML plug-in** [(Link)](https://github.com/hallvard/plantuml) solved the problem.

The required versions are the following: 
 - PlantUML Ecore Feature 1.1.25
 - PlantUML Feature 1.1.25
 - PlantUML JLatexMath Library Feature 1.0.7
 - PlantUML Library Feature 1.2021.5

Update site URL: [http://hallvard.github.io/plantuml ](http://hallvard.github.io/plantuml)

**Comment by grbeni** [comment]
@z3rone did you manage to solve the problem?
