### ISSUE TITLE
Annotations in XSTS

### ISSUE THREAD

**Issue by vincemolnar** [ftsrg/gamma#84]
We should consider adding annotations to XSTS to encode metadata related to the source model or the applied transformations. My proposed syntax is `//@myannotation`.

Possible uses:
* Remembering that the XSTS has been splitted into smaller transitions (influences back-annotation) - @szkupienpeti
* Describing the semantics of variable access (e.g. to create message queues) - @grbeni 

We should discuss how to implement these features and if they are really similar in nature.

**Comment by grbeni** [comment]
I agree, something very similar is already supported e.g., in the `Package` element of the statechart language metamodel: an annotation is placed in the root package element for back-annotation purposes if it contains a network of unfolded composite systems (first step in the transformation chain while deriving analysis models). The same approach could be introduced in the XSTS metamodel too.
